version: "3"
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    ports:
      - "27017:27017"
  server:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: server
    ports:
      - "5000:5000"
    links:
      - mongo
